#if !canImport(ObjectiveC)
import XCTest

extension VMwareFusionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VMwareFusionTests = [
        ("testHappyPath", testHappyPath),
        ("testMissingExecutable", testMissingExecutable),
        ("testNonZeroExit", testNonZeroExit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VMwareFusionTests.__allTests__VMwareFusionTests),
    ]
}
#endif
