---
name: Continuous Integration (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libssh Dependency
        run: brew install libssh
      - name: Build (Debug)
        run: swift build
      - name: Build (Release)
        run: swift build -c release
  test:
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libssh Dependency
        run: brew install libssh
      - name: Test
        run: swift test
